# PersistentVolumeClaim for PostgreSQL
# 일반 K8s 환경에서는 동적 프로비저닝을 사용합니다.
# StorageClass는 클라우드 환경에 맞게 설정하세요.
#
# 클라우드별 StorageClass 예시:
# - AWS EKS: gp2, gp3 (기본)
# - Azure AKS: managed, managed-premium
# - GCP GKE: standard-rwo, premium-rwo
# - Kind/Minikube: standard (기본)
# - On-premise: 클러스터 설정에 따라 다름
#
# storageClassName을 지정하지 않으면 클러스터의 기본 StorageClass를 사용합니다.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: backstage
spec:
  # storageClassName: gp3  # AWS EKS 예시
  # storageClassName: managed-premium  # Azure AKS 예시
  # storageClassName: standard-rwo  # GCP GKE 예시
  # 기본 StorageClass 사용 (주석 처리 또는 아래와 같이 빈 문자열)
  storageClassName: standard  # Kind/로컬 환경용 (변경 가능)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
